name: texas-holdem
services:
  - name: web
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 3001
    source_dir: /
    build_command: npm run build
    run_command: npm run start
    routes:
      - path: /
    envs:
      - key: NODE_ENV
        value: production
        scope: RUN_AND_BUILD_TIME
      - key: JWT_SECRET
        type: SECRET
        value: CHANGE_ME_TO_RANDOM_STRING
        scope: RUN_AND_BUILD_TIME
      - key: DATABASE_URL
        type: SECRET
        value: ${texas-holdem-db.DATABASE_URL}
        scope: RUN_AND_BUILD_TIME
databases:
  - name: texas-holdem-db
    engine: PG
    version: "15"
    size: db-s-dev-database
